-- =============================================================================
-- STUDENT ENROLMENTS + FEE LEDGER
--
-- Stops deriving a student's balance and starts recording it.
--
-- Today a balance is a FORMULA evaluated at read time:
--
--   published class_fees matched by the student's CURRENT class, for the
--   selected period, minus settled payments for that period
--
-- so the past is recomputed from today's data on every read. That is why there
-- is no promotion feature and why one cannot safely be added: the moment a
-- student's class changes, every historical balance recomputes against the new
-- class and a JSS1 debt is evaluated against JSS2's fee schedule.
--
-- Two tables fix it, following the shape every mature school system uses:
--
--   student_enrolments  which class a student was in, per academic session
--   student_charges     what they were actually charged — a row, not a formula
--
-- Charges are generated by trigger rather than app code because publishing a
-- fee is a client-side UPDATE (SchoolAdminDashboard handleApproveFee) and must
-- not be bypassable. Same reasoning as hash_student_pin and
-- protect_published_class_fees.
--
-- THE BACKFILL IS CORRECT BECAUSE THE BUG HAS NEVER FIRED. No promotion has
-- ever run, so every student's current class is the only class they have ever
-- had, and materialising today's derivation reproduces the truth exactly. That
-- stops being true the first time anyone edits a class by hand.
--
-- Idempotent. Staging via `supabase db push`; production via the SQL editor.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Tables
-- ---------------------------------------------------------------------------

create table if not exists public.student_enrolments (
  id uuid primary key default gen_random_uuid(),
  school_id uuid not null references public.schools (id) on delete cascade,
  student_id uuid not null references public.students (id) on delete cascade,
  -- restrict, not cascade: a period with enrolments attached must not be
  -- deletable, for the same reason payments pin their period (20260803140000).
  session_id uuid not null references public.sessions (id) on delete restrict,
  class text not null,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  unique (student_id, session_id)
);

comment on table public.student_enrolments is
  'Which class a student was in, per academic session. One row per student per '
  'session. Promotion INSERTS the next session rather than updating this one, '
  'so history is never rewritten.';

create index if not exists student_enrolments_school_session_idx
  on public.student_enrolments (school_id, session_id);
create index if not exists student_enrolments_student_idx
  on public.student_enrolments (student_id);

create table if not exists public.student_charges (
  id uuid primary key default gen_random_uuid(),
  school_id uuid not null references public.schools (id) on delete cascade,
  student_id uuid not null references public.students (id) on delete cascade,
  class_fee_id uuid not null references public.class_fees (id) on delete restrict,
  -- Copied from the fee, which may legitimately have neither (legacy rows).
  session_id uuid references public.sessions (id) on delete restrict,
  term_id uuid references public.terms (id) on delete restrict,
  -- The class as at the moment of charging. Kept so a charge explains itself
  -- after the student has been promoted away from it.
  class_at_charge text not null,
  -- Stored, not joined, so a charge is self-contained history.
  amount numeric not null,
  created_at timestamptz not null default now(),
  -- Makes charge generation idempotent, which every path below relies on.
  unique (student_id, class_fee_id)
);

comment on table public.student_charges is
  'The fee ledger: what a student was actually charged. Balance is '
  'sum(charges) - sum(payments), read rather than recomputed, so promotion, '
  'class corrections and fee edits cannot rewrite what was owed.';

create index if not exists student_charges_student_idx
  on public.student_charges (student_id);
create index if not exists student_charges_school_period_idx
  on public.student_charges (school_id, session_id, term_id);

-- ---------------------------------------------------------------------------
-- 2. Helpers
-- ---------------------------------------------------------------------------

-- A school's current session. The add-student insert does not set
-- students.session_id, so new enrolments have to resolve it.
create or replace function public.current_session_for_school(p_school_id uuid)
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select id
    from public.sessions
   where school_id = p_school_id
   order by is_current desc nulls last, start_year desc nulls last, created_at desc
   limit 1;
$$;

-- Charge one enrolment for every published fee of its session that targets its
-- class (or ALL). Idempotent.
--
-- Fees are matched on session_id EXACTLY, nulls excluded. That mirrors the
-- derivation being replaced: student-auth applies `.eq("session_id", ...)` when
-- a period is selected, and the dashboards always select one, so a fee with a
-- null session_id is already invisible and stays invisible.
create or replace function public.issue_charges_for_enrolment(
  p_school_id uuid,
  p_student_id uuid,
  p_session_id uuid,
  p_class text
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  insert into public.student_charges (
    school_id, student_id, class_fee_id, session_id, term_id, class_at_charge, amount
  )
  select cf.school_id, p_student_id, cf.id, cf.session_id, cf.term_id, p_class, cf.amount
    from public.class_fees cf
   where cf.school_id = p_school_id
     and cf.status = 'published'
     and cf.session_id = p_session_id
     and (cf.class_target = 'ALL' or cf.class_target = p_class)
  on conflict (student_id, class_fee_id) do nothing;

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

-- ---------------------------------------------------------------------------
-- 3. Triggers that keep the ledger complete
--
-- Three ways a charge can become due, so three triggers:
--   a fee is published        -> charge everyone already enrolled
--   a student is enrolled     -> charge them for fees already published
--   a student is created      -> enrol them, which fires the above
-- ---------------------------------------------------------------------------

create or replace function public.charge_students_on_fee_publish()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Only the pending -> published transition. Published fees are immutable
  -- (protect_published_class_fees), so this fires exactly once per fee.
  if new.status = 'published'
     and (tg_op = 'INSERT' or old.status is distinct from 'published')
     and new.session_id is not null
  then
    insert into public.student_charges (
      school_id, student_id, class_fee_id, session_id, term_id, class_at_charge, amount
    )
    select new.school_id, e.student_id, new.id, new.session_id, new.term_id, e.class, new.amount
      from public.student_enrolments e
      join public.students s on s.id = e.student_id
     where e.school_id = new.school_id
       and e.session_id = new.session_id
       and e.status = 'active'
       and coalesce(s.status, 'active') <> 'archived'
       and (new.class_target = 'ALL' or e.class = new.class_target)
    on conflict (student_id, class_fee_id) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists charge_students_on_fee_publish on public.class_fees;
create trigger charge_students_on_fee_publish
  after insert or update on public.class_fees
  for each row execute function public.charge_students_on_fee_publish();

create or replace function public.charge_student_on_enrolment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = 'active' then
    perform public.issue_charges_for_enrolment(
      new.school_id, new.student_id, new.session_id, new.class
    );
  end if;
  return new;
end;
$$;

drop trigger if exists charge_student_on_enrolment on public.student_enrolments;
create trigger charge_student_on_enrolment
  after insert on public.student_enrolments
  for each row execute function public.charge_student_on_enrolment();

create or replace function public.enrol_student_on_create()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session uuid;
begin
  -- students.session_id is not set by the add-student or bulk-upload paths, so
  -- fall back to the school's current session. A school with no sessions yet
  -- gets no enrolment; useAcademicPeriods seeds one on first dashboard load and
  -- the enrolment follows when a fee is published or the student is re-saved.
  v_session := coalesce(new.session_id, public.current_session_for_school(new.school_id));
  if v_session is null then
    return new;
  end if;

  insert into public.student_enrolments (school_id, student_id, session_id, class, status)
  values (new.school_id, new.id, v_session, new.class, 'active')
  on conflict (student_id, session_id) do nothing;

  return new;
end;
$$;

drop trigger if exists enrol_student_on_create on public.students;
create trigger enrol_student_on_create
  after insert on public.students
  for each row execute function public.enrol_student_on_create();

-- ---------------------------------------------------------------------------
-- 4. RLS — money, so read-only to members and unwritable from a browser
--
-- Same treatment as payments (20260803100000): SELECT for school members, and
-- NO insert/update/delete policy at all, so every write goes through the
-- triggers above or a service-role function.
-- ---------------------------------------------------------------------------

alter table public.student_enrolments enable row level security;
alter table public.student_charges enable row level security;

drop policy if exists eduledger_student_enrolments_select on public.student_enrolments;
create policy eduledger_student_enrolments_select on public.student_enrolments
  for select using (public.is_school_member(school_id));

drop policy if exists eduledger_student_charges_select on public.student_charges;
create policy eduledger_student_charges_select on public.student_charges
  for select using (public.is_school_member(school_id));

-- ---------------------------------------------------------------------------
-- 5. EXECUTE grants
--
-- Default privileges in public revoke EXECUTE from public/anon/authenticated
-- (20260803150000), but these are spelled out because a SECURITY DEFINER
-- function reachable from a browser is how create_student_session became an
-- anonymous session-minting oracle. service_role needs an explicit grant: it
-- bypasses RLS, not GRANTs.
-- ---------------------------------------------------------------------------

revoke all on function public.current_session_for_school(uuid) from public, anon, authenticated;
revoke all on function public.issue_charges_for_enrolment(uuid, uuid, uuid, text) from public, anon, authenticated;
revoke all on function public.charge_students_on_fee_publish() from public, anon, authenticated;
revoke all on function public.charge_student_on_enrolment() from public, anon, authenticated;
revoke all on function public.enrol_student_on_create() from public, anon, authenticated;

grant execute on function public.current_session_for_school(uuid) to service_role;
grant execute on function public.issue_charges_for_enrolment(uuid, uuid, uuid, text) to service_role;

-- ---------------------------------------------------------------------------
-- 6. Backfill
--
-- Reproduces today's derivation exactly, in three passes.
-- ---------------------------------------------------------------------------

-- (a) An enrolment for every session in which a student already has matching
--     published fees. This is what makes historical periods keep working: a
--     student who can see 2025/2026 fees today was, by definition, enrolled
--     then. The trigger above turns each of these into charges.
insert into public.student_enrolments (school_id, student_id, session_id, class, status)
select distinct s.school_id, s.id, cf.session_id, s.class, 'active'
  from public.students s
  -- Production carries students whose school_id names a school that does not
  -- exist (the hand-rebuild left students.school_id without a foreign key, and
  -- at least one id is a near-miss of a real one). They are unreachable — no
  -- school row means no portal and no login — but they would fail the FK below,
  -- so they are skipped and counted in the notice at the end.
  join public.schools sc on sc.id = s.school_id
  join public.class_fees cf
    on cf.school_id = s.school_id
   and cf.status = 'published'
   and cf.session_id is not null
   and (cf.class_target = 'ALL' or cf.class_target = s.class)
 where coalesce(s.status, 'active') <> 'archived'
   and s.class is not null
on conflict (student_id, session_id) do nothing;

-- (b) Every remaining active student gets an enrolment for the current session,
--     so a school with no fees yet still has a roster to promote later.
insert into public.student_enrolments (school_id, student_id, session_id, class, status)
select s.school_id, s.id,
       coalesce(s.session_id, public.current_session_for_school(s.school_id)),
       s.class, 'active'
  from public.students s
  join public.schools sc on sc.id = s.school_id
 where coalesce(s.status, 'active') <> 'archived'
   and s.class is not null
   and coalesce(s.session_id, public.current_session_for_school(s.school_id)) is not null
on conflict (student_id, session_id) do nothing;

-- (c) Safety net: charge anything the triggers did not, e.g. enrolments that
--     already existed from a partial earlier run of this migration.
insert into public.student_charges (
  school_id, student_id, class_fee_id, session_id, term_id, class_at_charge, amount
)
select cf.school_id, e.student_id, cf.id, cf.session_id, cf.term_id, e.class, cf.amount
  from public.student_enrolments e
  join public.students s on s.id = e.student_id
  join public.class_fees cf
    on cf.school_id = e.school_id
   and cf.session_id = e.session_id
   and cf.status = 'published'
   and (cf.class_target = 'ALL' or cf.class_target = e.class)
 where e.status = 'active'
   and coalesce(s.status, 'active') <> 'archived'
on conflict (student_id, class_fee_id) do nothing;

-- ---------------------------------------------------------------------------
-- 7. Reconciliation
--
-- The ledger must agree with the derivation it replaces, for every student, or
-- balances silently change the moment the edge functions start reading it.
-- This raises an exception rather than a notice: a mismatch means the backfill
-- is wrong, and shipping it would be worse than not shipping at all.
-- ---------------------------------------------------------------------------
do $$
declare
  v_mismatch integer;
  v_charges  integer;
  v_enrols   integer;
  v_orphans  integer;
begin
  select count(*) into v_mismatch
  from (
    -- what today's derivation says each active student owes, per fee
    select s.id as student_id, cf.id as fee_id
      from public.students s
      join public.schools sc on sc.id = s.school_id
      join public.class_fees cf
        on cf.school_id = s.school_id
       and cf.status = 'published'
       and cf.session_id is not null
       and (cf.class_target = 'ALL' or cf.class_target = s.class)
     where coalesce(s.status, 'active') <> 'archived'
       and s.class is not null
    except
    -- what the ledger says
    select c.student_id, c.class_fee_id
      from public.student_charges c
  ) missing;

  if v_mismatch > 0 then
    raise exception
      'Ledger backfill incomplete: % fee/student pairs derivable today are missing from student_charges. Migration aborted.',
      v_mismatch;
  end if;

  select count(*) into v_charges from public.student_charges;
  select count(*) into v_enrols  from public.student_enrolments;

  select count(*) into v_orphans
    from public.students s
   where not exists (select 1 from public.schools sc where sc.id = s.school_id);

  raise notice 'Ledger backfill OK: % enrolments, % charges, 0 mismatches.', v_enrols, v_charges;
  if v_orphans > 0 then
    raise notice
      'NOTE: % students belong to a school_id with no schools row and were skipped. They are already unreachable (no school = no portal, no login). Find them with: select id, student_id, school_id from public.students s where not exists (select 1 from public.schools sc where sc.id = s.school_id);',
      v_orphans;
  end if;
end;
$$;

-- Verify by hand afterwards — every student's ledger total vs the old formula:
--
--   select s.student_id, s.class,
--          (select coalesce(sum(cf.amount), 0)
--             from public.class_fees cf
--            where cf.school_id = s.school_id and cf.status = 'published'
--              and cf.session_id is not null
--              and (cf.class_target = 'ALL' or cf.class_target = s.class)) as derived_total,
--          (select coalesce(sum(c.amount), 0)
--             from public.student_charges c where c.student_id = s.id)      as ledger_total
--     from public.students s
--    where coalesce(s.status,'active') <> 'archived'
--   having ... -- compare the two columns; expect no rows where they differ
