// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifonivphhfplntzshtsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlmb25pdnBoaGZwbG50enNodHNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY1MjU5MjksImV4cCI6MjA5MjEwMTkyOX0.-0oRROCX5FmBTYX7Wpptj_oakRZbDg9bbi9Hp0sAHew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});